# .github/workflows/deploy.yml
name: DB Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start SQL Server with Docker
        run: |
          docker-compose -f docker/docker-compose.yml up -d
          sleep 20  # Wait for SQL Server to be fully up

      - name: Run SQL Scripts
        run: |
          ./scripts/deploy.sh

      - name: Clean up
        run: docker-compose down
